---
title: Asoh Black
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
destination: "./docs"
plugins:
- jekyll-assets
assets:
  digest: true
  compress:
    css: sass
    js: uglifier
