---
title: Asoh Black
timezone: UTC
collections:
  music:
    title: Music
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
destination: "./docs"
gems:
- jekyll-assets
assets:
  digest: true
