---
title: Asoh Black
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: NYC native, Asoh Black!, is one of Free.All.Mind$ most prominent musical
  artists. He's had a passion for hip-hop since high school when he discovered artists
  like Kanye West, Lil Wayne, Childish Gambino, Big Sean, and many more. After getting
  more into the music, Asoh developed a knack for writing lyrics and crafting feel-good
  records himself.
url: http://www.asohblack.com
destination: "./docs"
plugins:
- jekyll-assets
assets:
  digest: true
  compression: true
  gzip: true
  img:
    optim:
      jpegoptim:
        strip: all
    gifsicle:
      level: 1
webp:
  enabled: true
  quality: 75
  img_dir:
  - "/_uploads"
  - _assets/images
  formats:
  - ".jpeg"
  - ".jpg"
  - ".png"
  - ".tiff"
  gifs:
  - ".gif"
