---
title: Asoh Black
description: Asoh Black! One of F.A.M\$' prominent musical artists.
url: "http://www.asohblack.com"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
destination: './docs'
plugins:
  - jekyll-assets
assets:
  digest: true
  compression: true
  gzip: true
  img: { optim: { jpegoptim: { strip: all } }, gifsicle: { level: 1 } }
webp:
  enabled: true
  quality: 75
  img_dir: ["/_uploads", "_assets/images"]
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  gifs: [".gif"]